-- MySQL Script generated by MySQL Workbench
-- Thu May  4 11:36:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homedb` ;

-- -----------------------------------------------------
-- Schema homedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homedb` DEFAULT CHARACTER SET utf8 ;
USE `homedb` ;

-- -----------------------------------------------------
-- Table `homedb`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`log` ;

CREATE TABLE IF NOT EXISTS `homedb`.`log` (
  `sid` INT(11) NOT NULL,
  `state` TINYINT(1) NOT NULL,
  `val` DECIMAL(10,0) NULL,
  `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homedb`.`sensors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`sensors` ;

CREATE TABLE IF NOT EXISTS `homedb`.`sensors` (
  `sid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `fid` INT(11) NOT NULL,
  `rid` INT(11) NOT NULL,
  `xLoc` INT(11) NULL DEFAULT NULL,
  `yLoc` INT(11) NULL DEFAULT NULL,
  `sensorType` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homedb`.`alarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`alarm` ;

CREATE TABLE IF NOT EXISTS `homedb`.`alarm` (
  `sensors_sid` INT(10) UNSIGNED NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sensors_sid`),
  CONSTRAINT `fk_fire_sensors1`
    FOREIGN KEY (`sensors_sid`)
    REFERENCES `homedb`.`sensors` (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homedb`.`light`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`light` ;

CREATE TABLE IF NOT EXISTS `homedb`.`light` (
  `sensors_sid` INT(10) UNSIGNED NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  `maxVal` DECIMAL(2,0) NULL DEFAULT '50',
  PRIMARY KEY (`sensors_sid`),
  CONSTRAINT `fk_light_sensors`
    FOREIGN KEY (`sensors_sid`)
    REFERENCES `homedb`.`sensors` (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homedb`.`appliances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`appliances` ;

CREATE TABLE IF NOT EXISTS `homedb`.`appliances` (
  `sensors_sid` INT(10) UNSIGNED NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sensors_sid`),
  CONSTRAINT `fk_safety_sensors1`
    FOREIGN KEY (`sensors_sid`)
    REFERENCES `homedb`.`sensors` (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homedb`.`temp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`temp` ;

CREATE TABLE IF NOT EXISTS `homedb`.`temp` (
  `sensors_sid` INT(10) UNSIGNED NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  `curVal` DECIMAL(2,0) NULL DEFAULT '27',
  `preVal` DECIMAL(2,0) NULL DEFAULT '24',
  PRIMARY KEY (`sensors_sid`),
  CONSTRAINT `fk_currtemp_sensors1`
    FOREIGN KEY (`sensors_sid`)
    REFERENCES `homedb`.`sensors` (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homedb`.`updateq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`updateq` ;

CREATE TABLE IF NOT EXISTS `homedb`.`updateq` (
  `sid` INT(11) NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  `val` DECIMAL(10,0) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `homedb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedb`.`users` ;

CREATE TABLE IF NOT EXISTS `homedb`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(25) NOT NULL,
  `token` VARCHAR(30) NULL DEFAULT NULL,
  `ftoken` TEXT NULL DEFAULT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT '0',
  `is_approved` TINYINT(1) NULL DEFAULT '0',
  `createTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `homedb`;

DELIMITER $$

USE `homedb`$$
DROP TRIGGER IF EXISTS `homedb`.`sensors_AFTER_INSERT` $$
USE `homedb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `homedb`.`sensors_AFTER_INSERT` AFTER INSERT ON `sensors` FOR EACH ROW
BEGIN
SET @table = NEW.sensorType;
SET @id = NEW.sid;

IF (@table = "light") THEN
INSERT INTO `light`(sensors_sid) VALUES (@id);
END IF;

IF (@table = "alarm") THEN
INSERT INTO `alarm`(sensors_sid) VALUES (@id);
END IF;

IF (@table = "appliances") THEN
INSERT INTO `appliances`(sensors_sid) VALUES (@id);
END IF;

IF (@table = "temp") THEN
INSERT INTO `temp`(sensors_sid) VALUES (@id);
END IF;
END$$


USE `homedb`$$
DROP TRIGGER IF EXISTS `homedb`.`alarm_AFTER_UPDATE` $$
USE `homedb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `homedb`.`alarm_AFTER_UPDATE` AFTER UPDATE ON `alarm` FOR EACH ROW
-- Values in this table can only be changed by RPi
-- Inserts each update in the `log` table
BEGIN
INSERT INTO `homedb`.`log`(sid, state) VALUES(NEW.sensors_sid, NEW.state);
END$$


USE `homedb`$$
DROP TRIGGER IF EXISTS `homedb`.`light_AFTER_UPDATE` $$
USE `homedb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `homedb`.`light_AFTER_UPDATE` AFTER UPDATE ON `light` FOR EACH ROW
-- Values in this table can only be changed by `user`
-- Inserts each update in the `log` table,
-- and if state or maxVal changed then insert in `updateq` table also
BEGIN
IF (OLD.state != NEW.state OR OLD.maxVal != NEW.maxVal)
THEN
INSERT INTO `homedb`.`updateq`(sid, state, val) VALUES(NEW.sensors_sid, NEW.state, NEW.maxVal);
END IF;
INSERT INTO `homedb`.`log`(sid, state, val) VALUES(NEW.sensors_sid, NEW.state, NEW.maxVal);
END$$


USE `homedb`$$
DROP TRIGGER IF EXISTS `homedb`.`appliances_AFTER_UPDATE` $$
USE `homedb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `homedb`.`appliances_AFTER_UPDATE` AFTER UPDATE ON `appliances` FOR EACH ROW
-- Values in this table can only be changed by `user`
-- Inserts each update in the `log` table,
-- and if state changed then insert in `updateq` table also
BEGIN
IF (OLD.state != NEW.state)
THEN
INSERT INTO `homedb`.`updateq`(sid, state) VALUES(NEW.sensors_sid, NEW.state);
END IF;
INSERT INTO `homedb`.`log`(sid, state) VALUES(NEW.sensors_sid, NEW.state);
END$$


USE `homedb`$$
DROP TRIGGER IF EXISTS `homedb`.`temp_AFTER_UPDATE` $$
USE `homedb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `homedb`.`temp_AFTER_UPDATE` AFTER UPDATE ON `temp` FOR EACH ROW
-- Values in this table can only be changed by `user` or RPi
-- Inserts each update in the `log` table using changed state,
-- and if state or preVal changed then insert in `updateq` table also
BEGIN
IF (OLD.state != NEW.state OR OLD.preVal != NEW.preVal)
THEN
INSERT INTO `homedb`.`updateq`(sid, state, val) VALUES(NEW.sensors_sid, NEW.state, NEW.preVal);
INSERT INTO `homedb`.`log`(sid, state, val) VALUES(NEW.sensors_sid, NEW.state, NEW.preVal);
ELSE
INSERT INTO `homedb`.`log`(sid, state, val) VALUES(NEW.sensors_sid, NEW.state, NEW.curVal);
END IF;
DELETE FROM `homedb`.`log` WHERE `time` < DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 7 DAY);
END$$


USE `homedb`$$
DROP TRIGGER IF EXISTS `homedb`.`updateq_BEFORE_DELETE` $$
USE `homedb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `homedb`.`updateq_BEFORE_DELETE` BEFORE DELETE ON `updateq` FOR EACH ROW
BEGIN
-- INSERT INTO `homedb`.`log`(sid, state, val, time) VALUES(OLD.sid, OLD.state, OLD.val) ;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `homedb`.`sensors`
-- -----------------------------------------------------
START TRANSACTION;
USE `homedb`;
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (1, 'light_1', 1, 1, NULL, NULL, 'light');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (2, 'fire_1', 1, 1, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (3, 'temperature_1', 1, 1, NULL, NULL, 'temp');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (4, 'PIR_1 motion', 1, 1, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (5, 'home door', 1, 1, NULL, NULL, 'appliances');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (6, 'TV_1', 1, 1, NULL, NULL, 'appliances');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (7, 'light_2', 1, 2, NULL, NULL, 'light');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (8, 'fire_2', 1, 2, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (9, 'gasleakage', 1, 2, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (10, 'waterleakage_1', 1, 2, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (11, 'fridge', 1, 2, NULL, NULL, 'appliances');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (12, 'light_3', 1, 3, NULL, NULL, 'light');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (13, 'fire_3', 1, 3, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (14, 'PIR_2 motion', 1, 3, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (15, 'garage door', 1, 3, NULL, NULL, 'appliances');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (16, 'light_4', 2, 4, NULL, NULL, 'light');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (17, 'fire_4', 2, 4, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (18, 'temperature_4', 2, 4, NULL, NULL, 'temp');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (19, 'TV_4', 2, 4, NULL, NULL, 'appliances');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (20, 'light_5', 2, 5, NULL, NULL, 'light');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (21, 'fire_5', 2, 5, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (22, 'waterleakage_2', 2, 5, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (23, 'washer', 2, 5, NULL, NULL, 'appliances');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (24, 'light_6', 3, 6, NULL, NULL, 'light');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (25, 'fire_6', 3, 6, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (26, 'temperature_6', 3, 6, NULL, NULL, 'temp');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (27, 'TV_6', 3, 6, NULL, NULL, 'appliances');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (28, 'light_7', 3, 7, NULL, NULL, 'light');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (29, 'fire_7', 3, 7, NULL, NULL, 'alarm');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (30, 'temperature_7', 3, 7, NULL, NULL, 'temp');
INSERT INTO `homedb`.`sensors` (`sid`, `name`, `fid`, `rid`, `xLoc`, `yLoc`, `sensorType`) VALUES (31, 'TV_7', 3, 7, NULL, NULL, 'appliances');

COMMIT;


--
-- Dumping data for table `users`
--
START TRANSACTION;
USE `homedb`;
INSERT INTO `users` (`id`, `username`, `email`, `password`, `phone`, `token`, `ftoken`, `is_admin`, `is_approved`, `createTime`) VALUES
(1, 'Mustafa', 'mustafa@host.com', '1234', '01122334455', '0bd081ba20170422203235', NULL, 1, 1, '2017-04-22 17:16:31'),
(21, 'mustafakamel', 'must@host.com', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220', '8438', 'c1c0083d8507341120170428210551', NULL, 1, 1, '2017-04-28 18:59:06'),
(28, 'must', 'mu@host.com', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8', '1122334455', '8b2447d6f31660c820170502194257', NULL, 1, 1, '2017-04-28 19:14:06'),
(29, 'mustafaw', 'mustafak@host.com', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8', '1122334455', '4bdb7aee60fc999a20170501115424', NULL, 1, 1, '2017-05-01 09:54:24'),
(33, 'ahmedorabi94', 'eng.ahmedorabi94@gmail.com', 'f7c3bc1d808e04732adf679965ccc34ca7ae3441', '1011135949', '8b9e8a1aac1d41ba20170713060252', 'cZt8USwmras:APA91bE5kkDgvYV-ll3s3MOXV2_OqxdiYudPLR0AGhNoxBh70MDyzYYp0gbAmpIP9YTm9nMGmqblqZQThYYJsPb1f9ix5FxF6xm0TkVQQnhhr6bnnBoj_i6j9VXfXrWvl0ecD1ww5hFm', 1, 1, '2017-06-16 00:26:22'),
(35, 'ahmedali', 'eng.ahmedali94@gmail.com', 'f7c3bc1d808e04732adf679965ccc34ca7ae3441', '1011135949', '3bea4bde27d804d220170708182750', 'elC3PBRAVMo:APA91bFYaxsM-mGUsBJtuqZ_05CfGZOU4ddDK8rulRgluqp47ZlXD6R7Nz8SYcdDkYeKZb79FlY6gge_9ezNxy8sBWxCUIxlpep-QcWPuDySNMb6omlB1MH3Du_UF4FoRp8wim6uvWaH', 1, 1, '2017-06-25 05:20:23'),
(41, 'mohamedahmef', 'mohamedahmed@gmail.com', '7c222fb2927d828af22f592134e8932480637c0d', '1234567890', NULL, NULL, 0, 0, '2017-06-26 01:36:42'),
(42, 'ahmedmohamef', 'ahmedmohamef@gmail.com', '7c222fb2927d828af22f592134e8932480637c0d', '1234567890', NULL, NULL, 0, 0, '2017-06-26 01:39:50'),
(43, 'ahmedmahmoud', 'ahmedmahmoud@gmail.com', '7c222fb2927d828af22f592134e8932480637c0d', '1234567890', NULL, NULL, 0, 0, '2017-06-26 01:42:50'),
(44, 'ahmedsalem94', 'ahmedsalem94@gmail.com', '7c222fb2927d828af22f592134e8932480637c0d', '1234567890', '7a6569dedb69538b20170708024813', 'cZt8USwmras:APA91bE5kkDgvYV-ll3s3MOXV2_OqxdiYudPLR0AGhNoxBh70MDyzYYp0gbAmpIP9YTm9nMGmqblqZQThYYJsPb1f9ix5FxF6xm0TkVQQnhhr6bnnBoj_i6j9VXfXrWvl0ecD1ww5hFm', 0, 1, '2017-06-26 01:47:10'),
(46, 'Mustafaka', 'mostafak252@gmail.com', '6542d78b7470387798f60c4e2628806a0d58cee0', '123456789', '134bb5696b4d292120170703153927', 'jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj', 1, 1, '2017-06-26 08:24:59'),
(47, 'MustafaKE', 'mustafa@mu.mu', '44c91fef8a66f3915af5b33b4b1f4d989399bb5c', '123456789', NULL, NULL, 0, 1, '2017-06-30 07:10:44'),
(48, 'testing', 'test@tst.ss', '1056d1b12719b4e47619b8f0bdb7a4bad0f92391', '132132465', NULL, NULL, 0, 1, '2017-06-30 08:14:40'),
(49, 'eidarous', 'eidarousdev@gmail.com', '3c01c4266d1ce73e2378d483ea6cb57a4464e2de', '1212097284', NULL, NULL, 1, 1, '2017-06-30 12:29:13'),
(50, 'ahmedrafa', 'ahmedrafa94@gmail.com', 'e7b62e0745dc5edec905b1cd1c4a14fd99b32595', '1011135949', NULL, NULL, 1, 1, '2017-06-30 12:37:02'),
(51, 'anas.khedr', 'anaskhedr47@gmail.com', '4326aaaeab342a4eb9b28622387fa9cd7e904cca', '1002127025', 'c54d2189fa275cd720170711034001', 'cuo3MMKPEVo:APA91bHdGRTDuBDuzFFVtXWbPby1q45lXKLlCu86oVdfHU1al-KZ0Dh5JpJmIur919YMyFvhOyYCCAwG-K7sYA-Vq__zjvINzE4IQnZdH-ng8rJFy5ReVYMwBfoRBZyMR9NbBVJwzKog', 1, 1, '2017-06-30 15:49:29'),
(52, 'mohamedasd', 'mohamedasd@gmail.com', '7c222fb2927d828af22f592134e8932480637c0d', '1011135949', '832a02bee41345b020170701223411', 'fV_qMyz-zx0:APA91bGeVyv2_t58OIr3CXnIT6HI9jhF3kRkiq0g22GPQrBskTh5sq2hj9U5I-saJu8h7aCV6-Z6Mp02Mdh2On01UQ2mYCNQqYrs3r00cCrmI9ZvFIjbjK0Re722Sf--FLm2ah6QsxIv', 1, 1, '2017-07-01 22:27:26'),
(53, 'mohamedqwe', 'mohamedqwe@gmail.com', '7c222fb2927d828af22f592134e8932480637c0d', '1011135949', NULL, NULL, 0, 0, '2017-07-01 22:29:12'),
(55, 'mohamedbnm', 'mohamedbnm@gmail.com', '7c222fb2927d828af22f592134e8932480637c0d', '1011135949', NULL, NULL, 1, 1, '2017-07-01 22:32:06'),
(56, 'Sultan', 'sultanazb94@gmail.com', '682d515f8194b70695b85970e06da28bee1d5036', '1112457509', '54fa53d85e3006ed20170703180738', 'ezOyaLdO4Mo:APA91bFhXfcPcLicP5OWJK91nTEOhVingtWuy5DH20w-1LoRWQslB0629espl1NAQYP4L2obA_XB8zFotTnDHlvbRIb6Xt7Sc2x66Heq8XLdXWj4lfWXDfkl1Xf8aV-h1-4y0BFEpfBV', 1, 1, '2017-07-01 22:43:12'),
(57, 'ahmed', 'eng.ahmed@gmail.com', 'e2bc5a2ab76dec68d7d46aed1d6749038fd04bb1', '123456789', 'e24d54d70341e10e20170706170812', 'cZt8USwmras:APA91bE5kkDgvYV-ll3s3MOXV2_OqxdiYudPLR0AGhNoxBh70MDyzYYp0gbAmpIP9YTm9nMGmqblqZQThYYJsPb1f9ix5FxF6xm0TkVQQnhhr6bnnBoj_i6j9VXfXrWvl0ecD1ww5hFm', 1, 1, '2017-07-06 17:06:47'),
(58, 'mohamedali', 'mohamedali@gmail.com', 'e2bc5a2ab76dec68d7d46aed1d6749038fd04bb1', '123456789', NULL, NULL, 0, 0, '2017-07-06 17:11:45'),
(59, 'asdqwe', 'asdqwe@gmail.com', 'e2bc5a2ab76dec68d7d46aed1d6749038fd04bb1', '123456789', NULL, NULL, 0, 0, '2017-07-10 21:14:33'),
(60, 'mus94', 'mu94@host.com', '70ccd9007338d6d81dd3b6271621b9cf9a97ea00', '01100223300', NULL, NULL, 1, 1, '2017-07-10 22:03:44');

COMMIT;